### ISSUE TITLE
Refactoring of BaseApplication and ProcessStarter

### ISSUE THREAD

**Issue by EnnoxHD** [EnnoxHD/glyph-creator#7]
There is overlapping functionality in these classes. The goal is to improve the separation and clearity of functions. There are also some heavy code smells in them.
- [x] BaseApplication
- [x] ProcessStarter
- [x] clean up

**Comment by EnnoxHD** [comment]
```
Caused by: java.lang.NullPointerException: Cannot invoke "com.github.ennoxhd.glyphcreator.util.javafx.ProcessStarter.setIcon(String)" because the return value of "com.github.ennoxhd.glyphcreator.util.javafx.BaseApplication.getProcessStarter()" is null
        at com.github.ennoxhd.glyphcreator/com.github.ennoxhd.glyphcreator.util.javafx.BaseApplication.launch(BaseApplication.java:76)
        at com.github.ennoxhd.glyphcreator/com.github.ennoxhd.glyphcreator.app.GlyphCreatorApp.main(GlyphCreatorApp.java:21)
        ... 11 more
Exception running application com.github.ennoxhd.glyphcreator.app.GlyphCreatorApp
```
